version: 2

build: &build
  - setup_remote_docker
  - checkout
  - run:
      name: docker-build
      command: npx dockerfile-template -d BALENA_MACHINE_NAME="intel-nuc" | docker build -f - .
  - run:
      name: Install depedencies
      command: sudo apt-get install libdbus-1-dev
  - run:
      name: install-npm
      command: npm ci
  - run:
      name: test
      command: npm test

jobs:
  'node-10':
    working_directory: ~/node-10.15.0
    docker:
      - image: circleci/node:10.15.0
    steps: *build

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
