version: 2

build: &build
  - setup_remote_docker
  - checkout
  - run:
      name: install-npm
      command: npm ci
  - run:
      name: test
      command: npm test

jobs:
  "node-10":
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/node-10.15.0
    steps: *build

workflows:
  version: 2
  build:
    jobs:
      - "node-10"
